services:
  data_feed:
    build:
      context: .  # Path context for the Dockerfile
      dockerfile: Dockerfile.dev  # Path to the Dockerfile
    volumes:
      - .:/app  # Mount current directory as 'app/' for live code updates
      - /app/__pycache__  # Exclude Python cache
      - /app/.git  # Exclude git directory
      - poetry_cache:/root/.cache/pypoetry  # Cache Poetry dependencies
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
      - COMPOSE_BAKE=true
      - POETRY_VIRTUALENVS_CREATE=false  # Don't create virtualenvs in container
    ports:
      - "8000:8000"  # Adjust port if needed
    stdin_open: true  # Keep STDIN open
    tty: true # Allocate a pseudo-TTY

volumes:
  poetry_cache:  # Named volume for Poetry cache
